export const CREATE_CONTACT = 'CREATE_CONTACT';
export const CONTACTS_REQUEST = 'CONTACTS_REQUEST';
export const GET_CONTACTS_SUCCESS = 'GET_CONTACTS_SUCCESS';
export const GET_CONTACTS_FAILED = 'GET_CONTACTS_FAILED';
export const UPDATE_CONTACT = 'UPDATE_CONTACT';
export const DELETE_CONTACT = 'DELETE_CONTACT';
